heartbeat.monitors:

- type: http
  id: pac-man-welcome
  name: Pac-Man Welcome
  schedule: '@every 5s'
  urls: ['${PACMAN_WELCOME}']
  check.request:
    - method: GET
  check.response:
    status: [200]
    headers:
      'Content-Type': 'text/html'

- type: http
  id: event-handler-api
  name: Event Handler API
  schedule: '@every 5s'
  urls: ['${EVENT_HANDLER_API}']
  check.request:
    method: POST
  check.response:
    status: [200]
    headers:
      'Content-Type': 'application/json'

- type: http
  id: ksqldb-server-api
  name: ksqlDB Server API
  schedule: '@every 5s'
  urls: ['${KSQLDB_SERVER_API}']
  check.request:
    method: GET
  check.response:
    status: [200]
    headers:
      'Content-Type': 'application/json'

- type: http
  id: scoreboard-api
  name: Scoreboard API
  schedule: '@every 5s'
  urls: ['${SCOREBOARD_API}']
  check.request:
    method: POST
  check.response:
    status: [200]
    headers:
      'Content-Type': 'application/json'

processors:
- add_cloud_metadata: ~
- add_observer_metadata:
    cache.ttl: 5m
    geo:
      name: aws-us-east-1-zone
      location: 37.926868, -78.024902
      continent_name: North America
      country_iso_code: US
      region_name: N. Virginia
      region_iso_code: VA
      city_name: Mineral District

cloud.id: '${CLOUD_ID}'
cloud.auth: '${CLOUD_AUTH}'

output.elasticsearch:
  hosts: ["localhost:9200"]
